name: "Log Commit Message"
description: "Outputs the commit message"
inputs:
  COMMIT_MESSAGE:
    description: "The commit message to log"
    required: true
    default: "No commit message provided"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.COMMIT_MESSAGE }}
